name: Vulnerability Scanning and Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  unit-test:
    name: Build and Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        run: yarn test

  sast:
    name: Run Semgrep
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto

  sca:
    name: Run Dependency Scan
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "sebangku-gagahsyuja"
          format: "HTML"
          out: "reports"

      - name: Upload SCA report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports

  deploy-vercel:
    runs-on: ubuntu-latest
    needs: unit-test
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - name: Build Project
        run: vercel build --prod --token=$VERCEL_TOKEN

      - name: Deploy Project to Vercel
        run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
